CREATE TABLE IF NOT EXISTS loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(100),
    employment_type VARCHAR(100),
    employer_name VARCHAR(255),
    salary DOUBLE PRECISION,
    credit_score INTEGER,
    existing_loans INTEGER,
    missed_emi INTEGER,
    requested_amount DOUBLE PRECISION,
    loan_purpose VARCHAR(255),
    tenure_months INTEGER,
    risk_score INTEGER,
    decision VARCHAR(40),
    explanation VARCHAR(1200),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS application_reasons (
    application_id BIGINT NOT NULL,
    reason VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS application_fraud_flags (
    application_id BIGINT NOT NULL,
    flag VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(80) NOT NULL,
    institution VARCHAR(255),
    created_at TIMESTAMP
);
