server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: credwise-ai
  datasource:
    url: jdbc:h2:mem:credwiseai;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    com.credwiseai: INFO
