package com.credwiseai.credwiseai.service;

import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class AiExplanationService {
    public String explain(int riskScore, String decision, List<String> reasons, List<String> fraudFlags) {
        String leadingReason = reasons.isEmpty() ? "available borrower signals" : reasons.get(0);
        String fraudContext = fraudFlags.isEmpty()
                ? "No fraud indicators were triggered by the mock rules engine."
                : "Fraud review is recommended because " + String.join(" ", fraudFlags);

        return "CredWise AI assigned a risk score of " + riskScore + " and marked the application as "
                + decision + ". The decision is primarily influenced by: " + leadingReason + " "
                + fraudContext + " This explanation is generated by deterministic mock logic and is ready "
                + "to be replaced with an LLM-backed narrative service.";
    }
}
